
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
    - uses: actions/checkout@v1
    - name: Install ARM toolchain
      run: rustup target add thumbv7em-none-eabihf
    - name: Check Fmt
      run: cargo fmt --all -- --check
    - name: Build lib
      run: cargo check --all-targets --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::new_ret_no_self
    - name: Build examples
      run: cargo build --examples --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --all-features

